# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Modifications: Copyright (c) 2026 Emiliano Molinaro/SDU eScience Center
# - Modified to integrate with this repository

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: trtllm-disagg
spec:
  services:
    Frontend:
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.8.1
    TRTLLMPrefillWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: prefill
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.8.1
          workingDir: /workspace/
          command:
          - python3
          - -m
          - dynamo.trtllm
          args:
            - --model-path
            - meta-llama/Llama-3.2-1B-Instruct
            - --served-model-name
            - meta-llama/Llama-3.2-1B-Instruct
            - --disaggregation-mode
            - prefill
    TRTLLMDecodeWorker:
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: decode
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.8.1
          workingDir: /workspace/
          command:
          - python3
          - -m
          - dynamo.trtllm
          args:
            - --model-path
            - meta-llama/Llama-3.2-1B-Instruct
            - --served-model-name
            - meta-llama/Llama-3.2-1B-Instruct
            - --disaggregation-mode
            - decode